#!/bin/bash
#$ -S /bin/bash

# - - - - - - - - - - - - - - - - - - - - -
# Load required modules
# - - - - - - - - - - - - - - - - - - - - -

module load samtools

# - - - - - - - - - - - - - - - - - - - - -
# Set paths
# - - - - - - - - - - - - - - - - - - - - -

pathbam=/ifs/data/proteomics/projects/Anna/Retrotransp-transcription/Breast/aluY/BAM/Normals
pathout=/ifs/data/proteomics/projects/Anna/Retrotransp-transcription/Breast/aluY/sorted_BAM/Normals

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Variables for processing the data in parallel
# DO NOT CHANGE!
# This code is meant to assign one sample to the analysis
# by listing all of the files in a directory (inputDir)
# and then finding the Nth one in the list. N will be
# assigned by the $SGE_TASK_ID variable generated by
# the SGE cluster.
# Note: $SGE_TASK_ID will only be assigned if the flag
# -t is used and the job is submitted by 'qsub -t 1:N script.sh'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Assign index variable
number=`expr $SGE_TASK_ID - 1`

# Generate ls of input files
files=(${pathbam}/*.bam)

# Get fastq file from index variable
sequence=${files[number]}

# Get the name of current working file
BN=`basename $sequence .bam`

#to sorted bam
samtools sort $sequence $pathout/${BN}.sort
